// GENERATED by scripts/gen_contracts.py from
// apis/status-taxonomy.json + apis/completion-events.asyncapi.yaml.
// DO NOT EDIT BY HAND - rerun the generator (Factory#160).
//
// Pinned single source of truth for the RFC-0001 completion-event envelope, its
// optional v1.1 token-usage block, and the lifecycle status classifiers
// (terminal/failed/running/review/queued). Mirrors the generated Python module.

export interface Usage {
  input_tokens?: number | null;
  output_tokens?: number | null;
  total_tokens?: number | null;
  cost_usd?: number | null;
  model?: string | null;
  [key: string]: unknown;
}

export interface CorrelationBlock {
  session_id?: string | null;
  issue_number?: number | null;
  aifactory_task_id?: string | null;
  branch?: string | null;
  pr_number?: number | null;
  tfactory_spec_id?: string | null;
  [key: string]: unknown;
}

export interface CompletionEvent {
  correlation_key: string;
  service: string;
  task_id: string;
  status: string;
  phase: string;
  updated_at: string;
  usage?: Usage | null;
  correlation?: CorrelationBlock | null;
  schema_version?: string | null;
  [key: string]: unknown;
}

// --- Status taxonomy (generated from apis/status-taxonomy.json) ---------------

export const FAILED_TOKENS: ReadonlySet<string> = new Set([
  "abort",
  "aborted",
  "block",
  "blocked",
  "cancel",
  "canceled",
  "cancelled",
  "discard",
  "discarded",
  "error",
  "errored",
  "fail",
  "failed",
  "failure",
  "reject",
  "rejected",
]);
export const DONE_TOKENS: ReadonlySet<string> = new Set([
  "accept",
  "accepted",
  "approved",
  "closed",
  "complete",
  "completed",
  "done",
  "emitted",
  "merged",
  "passed",
  "ready",
  "shipped",
  "skip",
  "skipped",
  "succeeded",
  "success",
  "triaged",
]);
export const REVIEW_TOKENS: ReadonlySet<string> = new Set([
  "awaiting",
  "review",
  "reviewing",
]);
export const QUEUED_TOKENS: ReadonlySet<string> = new Set([
  "backlog",
  "draft",
  "icebox",
  "pending",
  "queued",
  "todo",
]);
export const RUNNING_TOKENS: ReadonlySet<string> = new Set([
  "act",
  "building",
  "coding",
  "executing",
  "generating",
  "in_progress",
  "inprogress",
  "planning",
  "progress",
  "running",
  "started",
  "working",
]);
export const STUCK_TOKENS: ReadonlySet<string> = new Set([
  "stuck",
]);

const SPLIT_RE = /[\s_-]+/;

function tokens(status: string | null | undefined): Set<string> {
  if (!status) return new Set();
  return new Set(
    status
      .trim()
      .toLowerCase()
      .split(SPLIT_RE)
      .filter((t) => t.length > 0),
  );
}

function matches(status: string | null | undefined, vocab: ReadonlySet<string>): boolean {
  for (const t of tokens(status)) {
    if (vocab.has(t)) return true;
  }
  return false;
}

export function isFailed(status: string | null | undefined): boolean {
  return matches(status, FAILED_TOKENS);
}

export function isDone(status: string | null | undefined): boolean {
  return matches(status, DONE_TOKENS);
}

export function isReview(status: string | null | undefined): boolean {
  return matches(status, REVIEW_TOKENS);
}

export function isQueued(status: string | null | undefined): boolean {
  return matches(status, QUEUED_TOKENS);
}

export function isStuck(status: string | null | undefined): boolean {
  return matches(status, STUCK_TOKENS);
}

export function isTerminal(status: string | null | undefined): boolean {
  return isDone(status) || isFailed(status);
}

export function isFailureOrStuck(status: string | null | undefined): boolean {
  return isFailed(status) || isStuck(status);
}

export function isRunning(status: string | null | undefined): boolean {
  if (!status) return false;
  return !isTerminal(status) && !isReview(status) && !isQueued(status);
}

export function isActive(status: string | null | undefined): boolean {
  if (!status) return true;
  return !isTerminal(status) && !isReview(status) && !isQueued(status);
}
