"""Factory shared contracts: RFC-0001 completion event, token usage, status taxonomy.

GENERATED by scripts/gen_contracts.py from
apis/status-taxonomy.json + apis/completion-events.asyncapi.yaml.
DO NOT EDIT BY HAND - rerun the generator (Factory#160).

This is the pinned single source of truth for the cross-factory completion-event
envelope (RFC-0001), its optional v1.1 token-usage block, the usage rollup
helpers, and the lifecycle status classifiers (terminal/failed/running/review/
queued). Consumers (CFactory, AIFactory, PFactory, TFactory) pin this package
instead of hand-rolling divergent copies. Per-service migration off the
hand-rolled models is a tracked follow-on (see the package README).
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "CompletionEvent",
    "CorrelationBlock",
    "Usage",
    "add_usage",
    "is_active",
    "is_done",
    "is_failed",
    "is_failure_or_stuck",
    "is_queued",
    "is_review",
    "is_running",
    "is_stuck",
    "is_terminal",
    "rollup_usage",
]


class Usage(BaseModel):
    """Optional, additive (v1.1) per-stage LLM token / cost block."""

    model_config = ConfigDict(extra="allow")

    input_tokens: int | None = Field(default=None, description="Prompt tokens (fresh, non-cached).")
    output_tokens: int | None = Field(default=None, description="Completion tokens.")
    total_tokens: int | None = Field(default=None, description="Convenience total.")
    cost_usd: float | None = Field(default=None, description="Provider/estimated stage cost.")
    model: str | None = Field(default=None, description="Model id (optional).")


class CorrelationBlock(BaseModel):
    """Optional upstream/downstream chain links (all additive)."""

    model_config = ConfigDict(extra="allow")

    session_id: str | None = None
    issue_number: int | None = None
    aifactory_task_id: str | None = None
    branch: str | None = None
    pr_number: int | None = None
    tfactory_spec_id: str | None = None


class CompletionEvent(BaseModel):
    """RFC-0001 completion-event envelope.

    The six required fields are stable; new fields are additive and optional and
    unknown fields are preserved (``extra="allow"``) so a consumer never drops a
    field a newer emitter added. ``status`` is a free string (per-service
    vocabulary); classify it with the ``is_*`` helpers in this module.
    """

    model_config = ConfigDict(extra="allow")

    correlation_key: str = Field(description="Shared key - issue number or synthetic fallback.")
    service: str = Field(description="Emitting service: pfactory|aifactory|tfactory|cfactory.")
    task_id: str = Field(description="Emitter's local id (session/task/spec).")
    status: str = Field(description="Terminal status this service landed on (per-service vocab).")
    phase: str = Field(description="Pipeline phase the status belongs to.")
    updated_at: str = Field(description="ISO-8601 UTC timestamp of the terminal transition.")
    usage: Usage | None = None
    correlation: CorrelationBlock | None = None
    schema_version: str | None = Field(
        default=None, description="Absent implies v1; present only on a breaking change."
    )


# --- Token-usage rollup helpers (Factory#160) --------------------------------


def add_usage(a: Usage | None, b: Usage | None) -> Usage:
    """Sum two usage blocks field-wise (None treated as zero).

    Token fields and cost are added; ``model`` is carried from the first operand
    that has one (a rollup spans models, so no single model is authoritative).
    Used to roll per-worker / per-stage usage up to a task total.
    """
    left = a or Usage()
    right = b or Usage()

    def _add(x: int | None, y: int | None) -> int | None:
        if x is None and y is None:
            return None
        return (x or 0) + (y or 0)

    def _add_f(x: float | None, y: float | None) -> float | None:
        if x is None and y is None:
            return None
        return (x or 0.0) + (y or 0.0)

    return Usage(
        input_tokens=_add(left.input_tokens, right.input_tokens),
        output_tokens=_add(left.output_tokens, right.output_tokens),
        total_tokens=_add(left.total_tokens, right.total_tokens),
        cost_usd=_add_f(left.cost_usd, right.cost_usd),
        model=left.model or right.model,
    )


def rollup_usage(items: Iterable[Usage | None]) -> Usage:
    """Fold a sequence of usage blocks into a single total via :func:`add_usage`."""
    total = Usage()
    for item in items:
        total = add_usage(total, item)
    return total


# --- Status taxonomy ---------------------------------------------------------
# Token sets mirror CFactory's canonical status_taxonomy.py and are generated
# from apis/status-taxonomy.json (the hub source of truth).

_FAILED_TOKENS: frozenset[str] = frozenset(
    {
        "abort",
        "aborted",
        "block",
        "blocked",
        "cancel",
        "canceled",
        "cancelled",
        "discard",
        "discarded",
        "error",
        "errored",
        "fail",
        "failed",
        "failure",
        "reject",
        "rejected",
    }
)
_DONE_TOKENS: frozenset[str] = frozenset(
    {
        "accept",
        "accepted",
        "approved",
        "closed",
        "complete",
        "completed",
        "done",
        "emitted",
        "merged",
        "passed",
        "ready",
        "shipped",
        "skip",
        "skipped",
        "succeeded",
        "success",
        "triaged",
    }
)
_REVIEW_TOKENS: frozenset[str] = frozenset(
    {
        "awaiting",
        "review",
        "reviewing",
    }
)
_QUEUED_TOKENS: frozenset[str] = frozenset(
    {
        "backlog",
        "draft",
        "icebox",
        "pending",
        "queued",
        "todo",
    }
)
_RUNNING_TOKENS: frozenset[str] = frozenset(
    {
        "act",
        "building",
        "coding",
        "executing",
        "generating",
        "in_progress",
        "inprogress",
        "planning",
        "progress",
        "running",
        "started",
        "working",
    }
)
_STUCK_TOKENS: frozenset[str] = frozenset(
    {
        "stuck",
    }
)

_SPLIT_RE = re.compile(r"[\s_\-]+")


def _tokens(status: str | None) -> set[str]:
    """Normalize a status into its lowercase token set (split on space/_/-)."""
    if not status:
        return set()
    return {t for t in _SPLIT_RE.split(status.strip().lower()) if t}


def _matches(status: str | None, vocabulary: frozenset[str]) -> bool:
    return bool(_tokens(status) & vocabulary)


def is_failed(status: str | None) -> bool:
    """True for a failure / rejection / abort status."""
    return _matches(status, _FAILED_TOKENS)


def is_done(status: str | None) -> bool:
    """True for a successful / completed-OK status (healthy terminal)."""
    return _matches(status, _DONE_TOKENS)


def is_review(status: str | None) -> bool:
    """True for a parked-for-review status (awaiting a human/AI decision)."""
    return _matches(status, _REVIEW_TOKENS)


def is_queued(status: str | None) -> bool:
    """True for a queued / not-started status (no agent attached yet)."""
    return _matches(status, _QUEUED_TOKENS)


def is_stuck(status: str | None) -> bool:
    """True when an upstream explicitly marks a stage stuck."""
    return _matches(status, _STUCK_TOKENS)


def is_terminal(status: str | None) -> bool:
    """True when a stage has reached a terminal state (done OR failed)."""
    return is_done(status) or is_failed(status)


def is_failure_or_stuck(status: str | None) -> bool:
    """True for a failure/rejection/abort OR an explicit stuck marker."""
    return is_failed(status) or is_stuck(status)


def is_running(status: str | None) -> bool:
    """True when a stage is actively executing (present-but-unknown reads running)."""
    if not status:
        return False
    return not is_terminal(status) and not is_review(status) and not is_queued(status)


def is_active(status: str | None) -> bool:
    """True when a task may have a live agent to stream (missing status reads active)."""
    if not status:
        return True
    return not is_terminal(status) and not is_review(status) and not is_queued(status)
