#!/usr/bin/env python3
"""Generate the factory-contracts single source of truth (Factory#160, epic #154).

The completion-event / token-usage contract and the lifecycle status taxonomy are
currently hand-rolled per service and disagree at runtime (CFactory, AIFactory,
PFactory and TFactory each re-derive ``CompletionEvent`` / ``Usage``; the status
classifier was reimplemented five divergent times in CFactory alone). This script
generates ONE pinned, committed ``factory-contracts`` artifact from the hub's
canonical inputs so consumers can pin it instead of re-deriving:

    apis/completion-events.asyncapi.yaml  -> RFC-0001 CompletionEvent + Usage
    apis/status-taxonomy.json             -> lifecycle token sets + classifiers

Outputs (committed so consumers pin a known version):
    shared/factory-contracts/python/factory_contracts/__init__.py   (pydantic v2)
    shared/factory-contracts/ts/factory-contracts.ts                (TS types)

Generation is intentionally dependency-free: ``datamodel-code-generator`` /
``json-schema-to-typescript`` are NOT vendored into the hub devShell, and the two
contracts are small and stable, so a tiny self-contained emitter is preferable to
a heavy toolchain dependency. If those tools are later adopted fleet-wide this
module is the single place to swap the emitter; the generated public API is the
contract, not the generator.

The Python model is hand-shaped (not a blind schema dump) so it carries the
RFC-0001 envelope, the v1.1 optional ``usage`` block, the usage rollup helpers
(``add_usage`` / ``rollup_usage`` per the issue), and the status classifiers
(``is_terminal`` / ``is_failed`` / ...) mirroring CFactory's canonical
``status_taxonomy.py`` token sets. The token sets themselves are read from
``status-taxonomy.json`` at generation time, so the JSON stays the source of truth.

Usage:
    python scripts/gen_contracts.py            # regenerate in place
    python scripts/gen_contracts.py --check    # fail if the committed output is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_TAXONOMY_JSON = _REPO_ROOT / "apis" / "status-taxonomy.json"
_OUT_PY = (
    _REPO_ROOT / "shared" / "factory-contracts" / "python" / "factory_contracts" / "__init__.py"
)
_OUT_TS = _REPO_ROOT / "shared" / "factory-contracts" / "ts" / "factory-contracts.ts"

# Multi-line so the emitted docstring/comment line never exceeds the 100-col bar.
_GENERATED_BANNER = (
    "GENERATED by scripts/gen_contracts.py from\n"
    "apis/status-taxonomy.json + apis/completion-events.asyncapi.yaml.\n"
    "DO NOT EDIT BY HAND - rerun the generator (Factory#160)."
)
# TS comment banner: each line prefixed with '// ' (the docstring form is bare).
_GENERATED_BANNER_TS = _GENERATED_BANNER.replace("\n", "\n// ")

# The canonical state keys whose token sets drive both emitted artifacts. 'stuck'
# is intentionally a sibling state (anomaly heuristic), not part of terminal.
_STATE_ORDER = ("failed", "done", "review", "queued", "running", "stuck")


def _emit(message: str) -> None:
    # Generator CLI: its stdout report IS its purpose, so the no-print rule is
    # intentionally suppressed at the single output sink.
    print(message)  # noqa: T201


def load_taxonomy() -> dict[str, list[str]]:
    """Read the canonical token sets from ``status-taxonomy.json``.

    Returns a state -> sorted-token-list mapping for the states the generator
    emits, preserving the JSON as the single source of truth.
    """
    data = json.loads(_TAXONOMY_JSON.read_text(encoding="utf-8"))
    states = data["states"]
    return {state: sorted(states[state]["tokens"]) for state in _STATE_ORDER}


def _py_frozenset_literal(tokens: list[str]) -> str:
    """Render a token list as a stable, line-wrapped ``frozenset`` literal."""
    inner = ",\n".join(f'        "{tok}"' for tok in tokens)
    return "frozenset(\n    {\n" + inner + ",\n    }\n)"


def render_python(taxonomy: dict[str, list[str]]) -> str:
    """Render the pydantic v2 module + usage helpers + status classifiers."""
    token_blocks = "\n".join(
        f"_{state.upper()}_TOKENS: frozenset[str] = {_py_frozenset_literal(tokens)}"
        for state, tokens in taxonomy.items()
    )
    return _PY_TEMPLATE.format(banner=_GENERATED_BANNER, token_blocks=token_blocks)


def render_typescript(taxonomy: dict[str, list[str]]) -> str:
    """Render the TS types + token sets + classifier functions."""
    token_blocks = "\n".join(
        "export const {name}_TOKENS: ReadonlySet<string> = new Set([\n{items}\n]);".format(
            name=state.upper(),
            items="\n".join(f'  "{tok}",' for tok in tokens),
        )
        for state, tokens in taxonomy.items()
    )
    return _TS_TEMPLATE.format(banner=_GENERATED_BANNER_TS, token_blocks=token_blocks)


def _write_if_changed(path: Path, content: str, *, check: bool) -> bool:
    """Write *content* to *path* (mkdir -p). In check mode, never write.

    Returns True when the on-disk content already matches (or was written);
    False when it is stale (check mode only).
    """
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def generate(*, check: bool) -> int:
    """Generate (or verify) both artifacts. Returns a process exit code."""
    taxonomy = load_taxonomy()
    targets = ((_OUT_PY, render_python(taxonomy)), (_OUT_TS, render_typescript(taxonomy)))
    stale: list[Path] = []
    for path, content in targets:
        ok = _write_if_changed(path, content, check=check)
        if not ok:
            stale.append(path)
        elif not check:
            _emit(f"wrote {path.relative_to(_REPO_ROOT)}")
    if check and stale:
        for path in stale:
            _emit(f"STALE: {path.relative_to(_REPO_ROOT)} (run scripts/gen_contracts.py)")
        return 1
    if check:
        _emit("factory-contracts generated output is up to date")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if the committed output is stale; do not write.",
    )
    args = parser.parse_args(argv)
    return generate(check=args.check)


# --- Emitted Python module template ------------------------------------------
# Kept as one f-string-free .format template (the body contains many braces).
_PY_TEMPLATE = '''\
"""Factory shared contracts: RFC-0001 completion event, token usage, status taxonomy.

{banner}

This is the pinned single source of truth for the cross-factory completion-event
envelope (RFC-0001), its optional v1.1 token-usage block, the usage rollup
helpers, and the lifecycle status classifiers (terminal/failed/running/review/
queued). Consumers (CFactory, AIFactory, PFactory, TFactory) pin this package
instead of hand-rolling divergent copies. Per-service migration off the
hand-rolled models is a tracked follow-on (see the package README).
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "CompletionEvent",
    "CorrelationBlock",
    "Usage",
    "add_usage",
    "is_active",
    "is_done",
    "is_failed",
    "is_failure_or_stuck",
    "is_queued",
    "is_review",
    "is_running",
    "is_stuck",
    "is_terminal",
    "rollup_usage",
]


class Usage(BaseModel):
    """Optional, additive (v1.1) per-stage LLM token / cost block."""

    model_config = ConfigDict(extra="allow")

    input_tokens: int | None = Field(default=None, description="Prompt tokens (fresh, non-cached).")
    output_tokens: int | None = Field(default=None, description="Completion tokens.")
    total_tokens: int | None = Field(default=None, description="Convenience total.")
    cost_usd: float | None = Field(default=None, description="Provider/estimated stage cost.")
    model: str | None = Field(default=None, description="Model id (optional).")


class CorrelationBlock(BaseModel):
    """Optional upstream/downstream chain links (all additive)."""

    model_config = ConfigDict(extra="allow")

    session_id: str | None = None
    issue_number: int | None = None
    aifactory_task_id: str | None = None
    branch: str | None = None
    pr_number: int | None = None
    tfactory_spec_id: str | None = None


class CompletionEvent(BaseModel):
    """RFC-0001 completion-event envelope.

    The six required fields are stable; new fields are additive and optional and
    unknown fields are preserved (``extra="allow"``) so a consumer never drops a
    field a newer emitter added. ``status`` is a free string (per-service
    vocabulary); classify it with the ``is_*`` helpers in this module.
    """

    model_config = ConfigDict(extra="allow")

    correlation_key: str = Field(description="Shared key - issue number or synthetic fallback.")
    service: str = Field(description="Emitting service: pfactory|aifactory|tfactory|cfactory.")
    task_id: str = Field(description="Emitter's local id (session/task/spec).")
    status: str = Field(description="Terminal status this service landed on (per-service vocab).")
    phase: str = Field(description="Pipeline phase the status belongs to.")
    updated_at: str = Field(description="ISO-8601 UTC timestamp of the terminal transition.")
    usage: Usage | None = None
    correlation: CorrelationBlock | None = None
    schema_version: str | None = Field(
        default=None, description="Absent implies v1; present only on a breaking change."
    )


# --- Token-usage rollup helpers (Factory#160) --------------------------------


def add_usage(a: Usage | None, b: Usage | None) -> Usage:
    """Sum two usage blocks field-wise (None treated as zero).

    Token fields and cost are added; ``model`` is carried from the first operand
    that has one (a rollup spans models, so no single model is authoritative).
    Used to roll per-worker / per-stage usage up to a task total.
    """
    left = a or Usage()
    right = b or Usage()

    def _add(x: int | None, y: int | None) -> int | None:
        if x is None and y is None:
            return None
        return (x or 0) + (y or 0)

    def _add_f(x: float | None, y: float | None) -> float | None:
        if x is None and y is None:
            return None
        return (x or 0.0) + (y or 0.0)

    return Usage(
        input_tokens=_add(left.input_tokens, right.input_tokens),
        output_tokens=_add(left.output_tokens, right.output_tokens),
        total_tokens=_add(left.total_tokens, right.total_tokens),
        cost_usd=_add_f(left.cost_usd, right.cost_usd),
        model=left.model or right.model,
    )


def rollup_usage(items: Iterable[Usage | None]) -> Usage:
    """Fold a sequence of usage blocks into a single total via :func:`add_usage`."""
    total = Usage()
    for item in items:
        total = add_usage(total, item)
    return total


# --- Status taxonomy ---------------------------------------------------------
# Token sets mirror CFactory's canonical status_taxonomy.py and are generated
# from apis/status-taxonomy.json (the hub source of truth).

{token_blocks}

_SPLIT_RE = re.compile(r"[\\s_\\-]+")


def _tokens(status: str | None) -> set[str]:
    """Normalize a status into its lowercase token set (split on space/_/-)."""
    if not status:
        return set()
    return {{t for t in _SPLIT_RE.split(status.strip().lower()) if t}}


def _matches(status: str | None, vocabulary: frozenset[str]) -> bool:
    return bool(_tokens(status) & vocabulary)


def is_failed(status: str | None) -> bool:
    """True for a failure / rejection / abort status."""
    return _matches(status, _FAILED_TOKENS)


def is_done(status: str | None) -> bool:
    """True for a successful / completed-OK status (healthy terminal)."""
    return _matches(status, _DONE_TOKENS)


def is_review(status: str | None) -> bool:
    """True for a parked-for-review status (awaiting a human/AI decision)."""
    return _matches(status, _REVIEW_TOKENS)


def is_queued(status: str | None) -> bool:
    """True for a queued / not-started status (no agent attached yet)."""
    return _matches(status, _QUEUED_TOKENS)


def is_stuck(status: str | None) -> bool:
    """True when an upstream explicitly marks a stage stuck."""
    return _matches(status, _STUCK_TOKENS)


def is_terminal(status: str | None) -> bool:
    """True when a stage has reached a terminal state (done OR failed)."""
    return is_done(status) or is_failed(status)


def is_failure_or_stuck(status: str | None) -> bool:
    """True for a failure/rejection/abort OR an explicit stuck marker."""
    return is_failed(status) or is_stuck(status)


def is_running(status: str | None) -> bool:
    """True when a stage is actively executing (present-but-unknown reads running)."""
    if not status:
        return False
    return not is_terminal(status) and not is_review(status) and not is_queued(status)


def is_active(status: str | None) -> bool:
    """True when a task may have a live agent to stream (missing status reads active)."""
    if not status:
        return True
    return not is_terminal(status) and not is_review(status) and not is_queued(status)
'''


# --- Emitted TypeScript template ---------------------------------------------
_TS_TEMPLATE = """\
// {banner}
//
// Pinned single source of truth for the RFC-0001 completion-event envelope, its
// optional v1.1 token-usage block, and the lifecycle status classifiers
// (terminal/failed/running/review/queued). Mirrors the generated Python module.

export interface Usage {{
  input_tokens?: number | null;
  output_tokens?: number | null;
  total_tokens?: number | null;
  cost_usd?: number | null;
  model?: string | null;
  [key: string]: unknown;
}}

export interface CorrelationBlock {{
  session_id?: string | null;
  issue_number?: number | null;
  aifactory_task_id?: string | null;
  branch?: string | null;
  pr_number?: number | null;
  tfactory_spec_id?: string | null;
  [key: string]: unknown;
}}

export interface CompletionEvent {{
  correlation_key: string;
  service: string;
  task_id: string;
  status: string;
  phase: string;
  updated_at: string;
  usage?: Usage | null;
  correlation?: CorrelationBlock | null;
  schema_version?: string | null;
  [key: string]: unknown;
}}

// --- Status taxonomy (generated from apis/status-taxonomy.json) ---------------

{token_blocks}

const SPLIT_RE = /[\\s_-]+/;

function tokens(status: string | null | undefined): Set<string> {{
  if (!status) return new Set();
  return new Set(
    status
      .trim()
      .toLowerCase()
      .split(SPLIT_RE)
      .filter((t) => t.length > 0),
  );
}}

function matches(status: string | null | undefined, vocab: ReadonlySet<string>): boolean {{
  for (const t of tokens(status)) {{
    if (vocab.has(t)) return true;
  }}
  return false;
}}

export function isFailed(status: string | null | undefined): boolean {{
  return matches(status, FAILED_TOKENS);
}}

export function isDone(status: string | null | undefined): boolean {{
  return matches(status, DONE_TOKENS);
}}

export function isReview(status: string | null | undefined): boolean {{
  return matches(status, REVIEW_TOKENS);
}}

export function isQueued(status: string | null | undefined): boolean {{
  return matches(status, QUEUED_TOKENS);
}}

export function isStuck(status: string | null | undefined): boolean {{
  return matches(status, STUCK_TOKENS);
}}

export function isTerminal(status: string | null | undefined): boolean {{
  return isDone(status) || isFailed(status);
}}

export function isFailureOrStuck(status: string | null | undefined): boolean {{
  return isFailed(status) || isStuck(status);
}}

export function isRunning(status: string | null | undefined): boolean {{
  if (!status) return false;
  return !isTerminal(status) && !isReview(status) && !isQueued(status);
}}

export function isActive(status: string | null | undefined): boolean {{
  if (!status) return true;
  return !isTerminal(status) && !isReview(status) && !isQueued(status);
}}
"""


if __name__ == "__main__":
    sys.exit(main())
